/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const Link: typeof import('@inertiajs/vue3').Link
  const activate: typeof import('./routes/training/index').activate
  const api: typeof import('./routes/api/index').default
  const apiCredentials: typeof import('./routes/settings/api-credentials/index').default
  const appearance: typeof import('./routes/appearance/index').default
  const callback: typeof import('./routes/google/index').callback
  const computed: typeof import('vue').computed
  const confirm: typeof import('./routes/two-factor/index').confirm
  const confirmation: typeof import('./routes/password/index').confirmation
  const create: typeof import('./routes/training/index').create
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const dashboard: typeof import('./routes/index').dashboard
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const deleteMethod: typeof import('./routes/settings/api-credentials/index').deleteMethod
  const destroy: typeof import('./routes/profile/index').destroy
  const diff: typeof import('./routes/documents/index').diff
  const disable: typeof import('./routes/two-factor/index').disable
  const disconnect: typeof import('./routes/google/index').disconnect
  const documents: typeof import('./routes/documents/index').default
  const drive: typeof import('./routes/process/index').drive
  const edit: typeof import('./routes/user-password/index').edit
  const effectScope: typeof import('vue').effectScope
  const email: typeof import('./routes/password/index').email
  const enable: typeof import('./routes/two-factor/index').enable
  const exportMethod: typeof import('./routes/training/index').exportMethod
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getInitials: typeof import('./composables/useInitials').getInitials
  const getRouteNames: typeof import('./composables/useRoute').getRouteNames
  const google: typeof import('./routes/google/index').default
  const h: typeof import('vue').h
  const home: typeof import('./routes/index').home
  const index: typeof import('./routes/training/index').index
  const initializeTheme: typeof import('./composables/useAppearance').initializeTheme
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const llm: typeof import('./routes/api/llm/index').default
  const local: typeof import('./routes/storage/index').local
  const login: typeof import('./routes/two-factor/login/index').default
  const logout: typeof import('./routes/index').logout
  const markRaw: typeof import('vue').markRaw
  const models: typeof import('./routes/api/llm/index').models
  const nextTick: typeof import('vue').nextTick
  const notice: typeof import('./routes/verification/index').notice
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const password: typeof import('./routes/password/index').default
  const process: typeof import('./routes/process/index').default
  const profile: typeof import('./routes/profile/index').default
  const provide: typeof import('vue').provide
  const providers: typeof import('./routes/api/llm/index').providers
  const qrCode: typeof import('./routes/two-factor/index').qrCode
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const recoveryCodes: typeof import('./routes/two-factor/index').recoveryCodes
  const redirect: typeof import('./routes/google/index').redirect
  const ref: typeof import('vue').ref
  const regenerateRecoveryCodes: typeof import('./routes/two-factor/index').regenerateRecoveryCodes
  const register: typeof import('./routes/register/index').default
  const request: typeof import('./routes/password/index').request
  const reset: typeof import('./routes/password/index').reset
  const resolveComponent: typeof import('vue').resolveComponent
  const route: typeof import('ziggy-js').route
  const routeExists: typeof import('./composables/useRoute').routeExists
  const router: typeof import('@inertiajs/vue3').router
  const run: typeof import('./routes/process/index').run
  const secretKey: typeof import('./routes/two-factor/index').secretKey
  const send: typeof import('./routes/verification/index').send
  const settings: typeof import('./routes/settings/index').default
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const sheet: typeof import('./routes/process/index').sheet
  const show: typeof import('./routes/two-factor/index').show
  const storage: typeof import('./routes/storage/index').default
  const store: typeof import('./routes/two-factor/login/index').store
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const training: typeof import('./routes/training/index').default
  const triggerRef: typeof import('vue').triggerRef
  const twoFactor: typeof import('./routes/two-factor/index').default
  const unref: typeof import('vue').unref
  const unvalidate: typeof import('./routes/documents/index').unvalidate
  const update: typeof import('./routes/user-password/index').update
  const updateTheme: typeof import('./composables/useAppearance').updateTheme
  const upload: typeof import('./routes/process/index').upload
  const useActiveUrl: typeof import('./composables/useActiveUrl').useActiveUrl
  const useAppearance: typeof import('./composables/useAppearance').useAppearance
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useId: typeof import('vue').useId
  const useInitials: typeof import('./composables/useInitials').useInitials
  const useModel: typeof import('vue').useModel
  const usePage: typeof import('@inertiajs/vue3').usePage
  const useRoute: typeof import('./composables/useRoute').useRoute
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTwoFactorAuth: typeof import('./composables/useTwoFactorAuth').useTwoFactorAuth
  const userPassword: typeof import('./routes/user-password/index').default
  const validate: typeof import('./routes/documents/index').validate
  const verification: typeof import('./routes/verification/index').default
  const verify: typeof import('./routes/verification/index').verify
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ResolvedAppearance } from './composables/useAppearance'
  import('./composables/useAppearance')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getInitials: UnwrapRef<typeof import('./composables/useInitials')['getInitials']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly initializeTheme: UnwrapRef<typeof import('./composables/useAppearance')['initializeTheme']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly route: UnwrapRef<typeof import('ziggy-js')['route']>
    readonly router: UnwrapRef<typeof import('@inertiajs/vue3')['router']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateTheme: UnwrapRef<typeof import('./composables/useAppearance')['updateTheme']>
    readonly useActiveUrl: UnwrapRef<typeof import('./composables/useActiveUrl')['useActiveUrl']>
    readonly useAppearance: UnwrapRef<typeof import('./composables/useAppearance')['useAppearance']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useForm: UnwrapRef<typeof import('@inertiajs/vue3')['useForm']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInitials: UnwrapRef<typeof import('./composables/useInitials')['useInitials']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePage: UnwrapRef<typeof import('@inertiajs/vue3')['usePage']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTwoFactorAuth: UnwrapRef<typeof import('./composables/useTwoFactorAuth')['useTwoFactorAuth']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}